export const APP_LOADING = 'APP_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_CURRENT_PAGE_TITLE = 'CURRENT_PAGE_TITLE';
export const SET_SIDEBAR_SELECTED_INDEX = 'SET_SIDEBAR_SELECTED_INDEX';